[package]
name = "cranelift-filetests"
authors = ["The Cranelift Project Developers"]
version = "0.37.0"
description = "Test driver and implementations of the filetest commands"
license = "Apache-2.0 WITH LLVM-exception"
documentation = "https://cranelift.readthedocs.io/en/latest/testing.html#file-tests"
repository = "https://github.com/CraneStation/cranelift"
publish = false
edition = "2018"

[dependencies]
cranelift-codegen = { path = "../cranelift-codegen", version = "0.37.0", features = ["testing_hooks"] }
cranelift-reader = { path = "../cranelift-reader", version = "0.37.0" }
cranelift-preopt = { path = "../cranelift-preopt", version = "0.37.0" }
file-per-thread-logger = "0.1.2"
filecheck = "0.4.0"
num_cpus = "1.8.0"
log = "0.4.6"
